In [1]:
# Tensor
# 데이터를 저장하는 다차원 배열 또는 컨테이너
# 딥러닝이 학습할때 사용하는 자료구조
# 0차원 텐서 : 스칼라 25 - 단일 데이터
# 1차원 텐서(벡터) : 리스트 형태  [1,2,3,4]
# 2차원 텐서(행렬) : 행 과 열로 이루어진 데이터 표데이터, 흑백 이미지(가로픽셀 x 세로픽셀)
# 3차원 텐서 : 컬러이미지 흑백이미지 + 채널정보(R G B)
# 고차원 텐서 : 동영상 : 이미지개수 x 가로픽셀 x 세로픽셀 x 채널정보

# 데이터의 표준 형식 : 일관된 숫자 형식
# 효율적인 계산 : GPU 지원 병열연산에 유리
# 딥러닝 프레임워크 : 텐서플로, 파이토치

In [ ]:
%pip install torch torchvision

In [36]:
# 기본연산
import torch
# 빈 텐서 생성
x = torch.empty(3,4)
x

tensor([[3.8993e+25, 1.2724e-42, 3.8412e-01, 3.5774e-01],
        [7.3501e-01, 1.0821e-01, 8.3247e-01, 8.1851e-01],
        [6.2914e-01, 1.0362e-01, 4.8689e-01, 4.5083e-01]])

In [11]:
# 랜덤 텐서
x = torch.rand(3,4)
x

tensor([[0.4669, 0.5657, 0.1163, 0.0650],
        [0.7728, 0.6520, 0.0274, 0.6068],
        [0.2508, 0.3299, 0.3981, 0.4049]])

In [38]:
# 0으로 텐서 초기화
torch.zeros(3,4,dtype=torch.long)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

In [39]:
# 1로 채워진 텐서
x = torch.ones(3,4, dtype=torch.long)
x

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [43]:
import numpy as np
print( torch.tensor( [3.5,3,2.1] ) )
print( np.array( [3.5,3,2.1] )  )

tensor([3.5000, 3.0000, 2.1000])
[3.5 3.  2.1]


In [45]:
# 기존의 텐서를 기반으로 새로운 텐서 생성
x = torch.ones(3,4)
y = torch.randn_like(x, dtype= torch.float)
x,  y

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 tensor([[-0.0163,  0.0294, -1.7189,  0.2684],
         [-0.2964,  0.8398, -0.3335,  1.9050],
         [-0.0994, -1.9712, -0.9993, -1.2988]]))

In [47]:
import torch
x = torch.rand(3,4)
y = torch.rand(3,4)
x ,  y, x+y


(tensor([[0.4988, 0.1275, 0.3183, 0.2456],
         [0.1980, 0.1445, 0.9776, 0.9252],
         [0.9166, 0.3505, 0.7453, 0.4773]]),
 tensor([[0.6852, 0.2295, 0.0325, 0.8326],
         [0.3532, 0.5794, 0.7210, 0.5174],
         [0.3159, 0.5675, 0.8700, 0.1350]]),
 tensor([[1.1840, 0.3569, 0.3508, 1.0781],
         [0.5512, 0.7239, 1.6987, 1.4426],
         [1.2325, 0.9180, 1.6153, 0.6123]]))

In [48]:
torch.add(x,y)

tensor([[1.1840, 0.3569, 0.3508, 1.0781],
        [0.5512, 0.7239, 1.6987, 1.4426],
        [1.2325, 0.9180, 1.6153, 0.6123]])

In [49]:
#in-place   y = y + x   y += x
y.add_(x)

tensor([[1.1840, 0.3569, 0.3508, 1.0781],
        [0.5512, 0.7239, 1.6987, 1.4426],
        [1.2325, 0.9180, 1.6153, 0.6123]])

In [50]:
y

tensor([[1.1840, 0.3569, 0.3508, 1.0781],
        [0.5512, 0.7239, 1.6987, 1.4426],
        [1.2325, 0.9180, 1.6153, 0.6123]])

In [ ]:
# 행렬 곱셈 
x = torch.rand(3,4)
y = torch.rand(4,5)
x, y, torch.mm(x,y),x@y # 파이썬 3.5  x@y

(tensor([[0.4268, 0.6410, 0.9104, 0.9407],
         [0.5068, 0.3030, 0.5365, 0.5436],
         [0.4020, 0.0376, 0.3778, 0.5776]]),
 tensor([[0.7224, 0.2634, 0.4158, 0.1821, 0.7458],
         [0.9044, 0.8935, 0.7327, 0.9384, 0.5317],
         [0.6226, 0.4863, 0.4647, 0.4513, 0.0581],
         [0.6434, 0.5071, 0.0539, 0.0536, 0.5537]]),
 tensor([[2.0603, 1.6051, 1.1209, 1.1405, 1.2329],
         [1.3239, 0.9408, 0.7113, 0.6478, 0.8712],
         [0.9312, 0.6161, 0.4013, 0.3099, 0.6616]]),
 tensor([[2.0603, 1.6051, 1.1209, 1.1405, 1.2329],
         [1.3239, 0.9408, 0.7113, 0.6478, 0.8712],
         [0.9312, 0.6161, 0.4013, 0.3099, 0.6616]]))

In [62]:
# 슬라이싱 가능
x = torch.rand(4,5)
x[1,1], x[1,1].item(), type(x[1,1]), type(x[1,1].item() )

(tensor(0.2955), 0.29545629024505615, torch.Tensor, float)